CREATE TABLE IF NOT EXISTS show(
    _id       INTEGER PRIMARY KEY AUTOINCREMENT,
    show_name TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS audio (
    _id      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    show_id  INTEGER REFERENCES show (_id) NOT NULL,
    filePath TEXT    NOT NULL,
    preWait  REAL    DEFAULT (0) NOT NULL,
    fadeIn   REAL    DEFAULT (0) NOT NULL,
    fadeOut  REAL    NOT NULL DEFAULT (0),
    postWait REAL    DEFAULT (0) NOT NULL,
    volume   REAL    DEFAULT (0.9)  NOT NULL
);

CREATE TABLE IF NOT EXISTS midi (
    _id     INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    show_id INTEGER REFERENCES show (_id) NOT NULL,
    data    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS cue (
    _id       INTEGER PRIMARY KEY AUTOINCREMENT,
    show_id   INTEGER REFERENCES show (_id),
    cueNumber INTEGER NOT NULL,
    cueName   TEXT,
    audioCue  INTEGER REFERENCES audio (_id) 
);